# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    import book_pb2 as book__pb2
except ImportError:
    from proto import book_pb2 as book__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in book_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookServiceStub(object):
    """──────────────────────────────────────────────────────────
    BookService  –  exposed by the Book service
    consumed by any downstream micro-service
    ──────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBook = channel.unary_unary(
                '/book.BookService/GetBook',
                request_serializer=book__pb2.GetBookRequest.SerializeToString,
                response_deserializer=book__pb2.BookPayload.FromString,
                _registered_method=True)
        self.GetBooksByAuthor = channel.unary_unary(
                '/book.BookService/GetBooksByAuthor',
                request_serializer=book__pb2.GetBooksByAuthorRequest.SerializeToString,
                response_deserializer=book__pb2.BookListResponse.FromString,
                _registered_method=True)
        self.SearchBooks = channel.unary_unary(
                '/book.BookService/SearchBooks',
                request_serializer=book__pb2.SearchBooksRequest.SerializeToString,
                response_deserializer=book__pb2.BookListResponse.FromString,
                _registered_method=True)
        self.GetAuthor = channel.unary_unary(
                '/book.BookService/GetAuthor',
                request_serializer=book__pb2.GetAuthorRequest.SerializeToString,
                response_deserializer=book__pb2.AuthorPayload.FromString,
                _registered_method=True)
        self.GetPublisher = channel.unary_unary(
                '/book.BookService/GetPublisher',
                request_serializer=book__pb2.GetPublisherRequest.SerializeToString,
                response_deserializer=book__pb2.PublisherPayload.FromString,
                _registered_method=True)


class BookServiceServicer(object):
    """──────────────────────────────────────────────────────────
    BookService  –  exposed by the Book service
    consumed by any downstream micro-service
    ──────────────────────────────────────────────────────────
    """

    def GetBook(self, request, context):
        """Get a book by ISBN
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBooksByAuthor(self, request, context):
        """Get all books by an author id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchBooks(self, request, context):
        """Search books by title keyword
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuthor(self, request, context):
        """Get an author by id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPublisher(self, request, context):
        """Get a publisher by name
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBook,
                    request_deserializer=book__pb2.GetBookRequest.FromString,
                    response_serializer=book__pb2.BookPayload.SerializeToString,
            ),
            'GetBooksByAuthor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBooksByAuthor,
                    request_deserializer=book__pb2.GetBooksByAuthorRequest.FromString,
                    response_serializer=book__pb2.BookListResponse.SerializeToString,
            ),
            'SearchBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchBooks,
                    request_deserializer=book__pb2.SearchBooksRequest.FromString,
                    response_serializer=book__pb2.BookListResponse.SerializeToString,
            ),
            'GetAuthor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthor,
                    request_deserializer=book__pb2.GetAuthorRequest.FromString,
                    response_serializer=book__pb2.AuthorPayload.SerializeToString,
            ),
            'GetPublisher': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublisher,
                    request_deserializer=book__pb2.GetPublisherRequest.FromString,
                    response_serializer=book__pb2.PublisherPayload.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'book.BookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('book.BookService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookService(object):
    """──────────────────────────────────────────────────────────
    BookService  –  exposed by the Book service
    consumed by any downstream micro-service
    ──────────────────────────────────────────────────────────
    """

    @staticmethod
    def GetBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book.BookService/GetBook',
            book__pb2.GetBookRequest.SerializeToString,
            book__pb2.BookPayload.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBooksByAuthor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book.BookService/GetBooksByAuthor',
            book__pb2.GetBooksByAuthorRequest.SerializeToString,
            book__pb2.BookListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book.BookService/SearchBooks',
            book__pb2.SearchBooksRequest.SerializeToString,
            book__pb2.BookListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuthor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book.BookService/GetAuthor',
            book__pb2.GetAuthorRequest.SerializeToString,
            book__pb2.AuthorPayload.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPublisher(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book.BookService/GetPublisher',
            book__pb2.GetPublisherRequest.SerializeToString,
            book__pb2.PublisherPayload.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
