# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import book_v3_pb2 as proto_dot_book__v3__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/book_v3_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookV3ServiceStub(object):
    """Book Service V3 contract for internal consumers (RAG, recommendation, etc.)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBookByWorkId = channel.unary_unary(
                '/bookv3.BookV3Service/GetBookByWorkId',
                request_serializer=proto_dot_book__v3__pb2.GetBookByWorkIdRequest.SerializeToString,
                response_deserializer=proto_dot_book__v3__pb2.BookV3Payload.FromString,
                _registered_method=True)
        self.ListBooks = channel.unary_unary(
                '/bookv3.BookV3Service/ListBooks',
                request_serializer=proto_dot_book__v3__pb2.ListBooksRequest.SerializeToString,
                response_deserializer=proto_dot_book__v3__pb2.BookV3ListResponse.FromString,
                _registered_method=True)
        self.SearchBooks = channel.unary_unary(
                '/bookv3.BookV3Service/SearchBooks',
                request_serializer=proto_dot_book__v3__pb2.SearchBooksRequest.SerializeToString,
                response_deserializer=proto_dot_book__v3__pb2.BookV3ListResponse.FromString,
                _registered_method=True)


class BookV3ServiceServicer(object):
    """Book Service V3 contract for internal consumers (RAG, recommendation, etc.)
    """

    def GetBookByWorkId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookV3ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBookByWorkId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookByWorkId,
                    request_deserializer=proto_dot_book__v3__pb2.GetBookByWorkIdRequest.FromString,
                    response_serializer=proto_dot_book__v3__pb2.BookV3Payload.SerializeToString,
            ),
            'ListBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBooks,
                    request_deserializer=proto_dot_book__v3__pb2.ListBooksRequest.FromString,
                    response_serializer=proto_dot_book__v3__pb2.BookV3ListResponse.SerializeToString,
            ),
            'SearchBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchBooks,
                    request_deserializer=proto_dot_book__v3__pb2.SearchBooksRequest.FromString,
                    response_serializer=proto_dot_book__v3__pb2.BookV3ListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bookv3.BookV3Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bookv3.BookV3Service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookV3Service(object):
    """Book Service V3 contract for internal consumers (RAG, recommendation, etc.)
    """

    @staticmethod
    def GetBookByWorkId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookv3.BookV3Service/GetBookByWorkId',
            proto_dot_book__v3__pb2.GetBookByWorkIdRequest.SerializeToString,
            proto_dot_book__v3__pb2.BookV3Payload.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookv3.BookV3Service/ListBooks',
            proto_dot_book__v3__pb2.ListBooksRequest.SerializeToString,
            proto_dot_book__v3__pb2.BookV3ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookv3.BookV3Service/SearchBooks',
            proto_dot_book__v3__pb2.SearchBooksRequest.SerializeToString,
            proto_dot_book__v3__pb2.BookV3ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
