# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/book_v3.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/book_v3.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/book_v3.proto\x12\x06\x62ookv3\")\n\x16GetBookByWorkIdRequest\x12\x0f\n\x07work_id\x18\x01 \x01(\t\"/\n\x10ListBooksRequest\x12\x0c\n\x04skip\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\"@\n\x12SearchBooksRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0c\n\x04skip\x18\x02 \x01(\x05\x12\r\n\x05limit\x18\x03 \x01(\x05\"\xa3\x01\n\rBookV3Payload\x12\x0f\n\x07work_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x16\n\x0eprimary_author\x18\x03 \x01(\t\x12\x0f\n\x07\x61uthors\x18\x04 \x03(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x0e\n\x06genres\x18\x06 \x03(\t\x12\x0e\n\x06themes\x18\x07 \x03(\t\x12\x14\n\x0crag_document\x18\x08 \x01(\t\"I\n\x12\x42ookV3ListResponse\x12$\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x15.bookv3.BookV3Payload\x12\r\n\x05total\x18\x02 \x01(\x05\x32\xe3\x01\n\rBookV3Service\x12H\n\x0fGetBookByWorkId\x12\x1e.bookv3.GetBookByWorkIdRequest\x1a\x15.bookv3.BookV3Payload\x12\x41\n\tListBooks\x12\x18.bookv3.ListBooksRequest\x1a\x1a.bookv3.BookV3ListResponse\x12\x45\n\x0bSearchBooks\x12\x1a.bookv3.SearchBooksRequest\x1a\x1a.bookv3.BookV3ListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.book_v3_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETBOOKBYWORKIDREQUEST']._serialized_start=31
  _globals['_GETBOOKBYWORKIDREQUEST']._serialized_end=72
  _globals['_LISTBOOKSREQUEST']._serialized_start=74
  _globals['_LISTBOOKSREQUEST']._serialized_end=121
  _globals['_SEARCHBOOKSREQUEST']._serialized_start=123
  _globals['_SEARCHBOOKSREQUEST']._serialized_end=187
  _globals['_BOOKV3PAYLOAD']._serialized_start=190
  _globals['_BOOKV3PAYLOAD']._serialized_end=353
  _globals['_BOOKV3LISTRESPONSE']._serialized_start=355
  _globals['_BOOKV3LISTRESPONSE']._serialized_end=428
  _globals['_BOOKV3SERVICE']._serialized_start=431
  _globals['_BOOKV3SERVICE']._serialized_end=658
# @@protoc_insertion_point(module_scope)
