# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'book.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x04\x62ook\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\t\"I\n\x17GetBooksByAuthorRequest\x12\x11\n\tauthor_id\x18\x01 \x01(\x05\x12\x0c\n\x04skip\x18\x02 \x01(\x05\x12\r\n\x05limit\x18\x03 \x01(\x05\"@\n\x12SearchBooksRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0c\n\x04skip\x18\x02 \x01(\x05\x12\r\n\x05limit\x18\x03 \x01(\x05\"%\n\x10GetAuthorRequest\x12\x11\n\tauthor_id\x18\x01 \x01(\x05\"#\n\x13GetPublisherRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"s\n\x0b\x42ookPayload\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\x05\x12\x11\n\tauthor_id\x18\x04 \x01(\x05\x12\x13\n\x0b\x61uthor_name\x18\x05 \x01(\t\x12\x11\n\tpublisher\x18\x06 \x01(\t\"x\n\rAuthorPayload\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x03 \x01(\t\x12\x11\n\tyear_born\x18\x04 \x01(\x05\x12\x11\n\tyear_died\x18\x05 \x01(\x05\x12\x16\n\x0etype_of_writer\x18\x06 \x01(\t\"H\n\x10PublisherPayload\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t\x12\x14\n\x0cyear_founded\x18\x03 \x01(\x05\"C\n\x10\x42ookListResponse\x12 \n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x11.book.BookPayload\x12\r\n\x05total\x18\x02 \x01(\x05\x32\xca\x02\n\x0b\x42ookService\x12\x32\n\x07GetBook\x12\x14.book.GetBookRequest\x1a\x11.book.BookPayload\x12I\n\x10GetBooksByAuthor\x12\x1d.book.GetBooksByAuthorRequest\x1a\x16.book.BookListResponse\x12?\n\x0bSearchBooks\x12\x18.book.SearchBooksRequest\x1a\x16.book.BookListResponse\x12\x38\n\tGetAuthor\x12\x16.book.GetAuthorRequest\x1a\x13.book.AuthorPayload\x12\x41\n\x0cGetPublisher\x12\x19.book.GetPublisherRequest\x1a\x16.book.PublisherPayloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETBOOKREQUEST']._serialized_start=20
  _globals['_GETBOOKREQUEST']._serialized_end=50
  _globals['_GETBOOKSBYAUTHORREQUEST']._serialized_start=52
  _globals['_GETBOOKSBYAUTHORREQUEST']._serialized_end=125
  _globals['_SEARCHBOOKSREQUEST']._serialized_start=127
  _globals['_SEARCHBOOKSREQUEST']._serialized_end=191
  _globals['_GETAUTHORREQUEST']._serialized_start=193
  _globals['_GETAUTHORREQUEST']._serialized_end=230
  _globals['_GETPUBLISHERREQUEST']._serialized_start=232
  _globals['_GETPUBLISHERREQUEST']._serialized_end=267
  _globals['_BOOKPAYLOAD']._serialized_start=269
  _globals['_BOOKPAYLOAD']._serialized_end=384
  _globals['_AUTHORPAYLOAD']._serialized_start=386
  _globals['_AUTHORPAYLOAD']._serialized_end=506
  _globals['_PUBLISHERPAYLOAD']._serialized_start=508
  _globals['_PUBLISHERPAYLOAD']._serialized_end=580
  _globals['_BOOKLISTRESPONSE']._serialized_start=582
  _globals['_BOOKLISTRESPONSE']._serialized_end=649
  _globals['_BOOKSERVICE']._serialized_start=652
  _globals['_BOOKSERVICE']._serialized_end=982
# @@protoc_insertion_point(module_scope)
