# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/book_v4.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/book_v4.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/book_v4.proto\x12\x06\x62ookv4\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\t\")\n\x16GetBookByWorkIdRequest\x12\x0f\n\x07work_id\x18\x01 \x01(\t\"4\n\x0fGetBookResponse\x12!\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x13.bookv4.BookPayload\"\x87\x01\n\x0b\x42ookPayload\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\x0f\n\x07work_id\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x16\n\x0eprimary_author\x18\x04 \x01(\t\x12\x0f\n\x07\x61uthors\x18\x05 \x03(\t\x12\x0c\n\x04year\x18\x06 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x07 \x01(\t2\x95\x01\n\x0b\x42ookService\x12:\n\x07GetBook\x12\x16.bookv4.GetBookRequest\x1a\x17.bookv4.GetBookResponse\x12J\n\x0fGetBookByWorkId\x12\x1e.bookv4.GetBookByWorkIdRequest\x1a\x17.bookv4.GetBookResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.book_v4_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETBOOKREQUEST']._serialized_start=31
  _globals['_GETBOOKREQUEST']._serialized_end=61
  _globals['_GETBOOKBYWORKIDREQUEST']._serialized_start=63
  _globals['_GETBOOKBYWORKIDREQUEST']._serialized_end=104
  _globals['_GETBOOKRESPONSE']._serialized_start=106
  _globals['_GETBOOKRESPONSE']._serialized_end=158
  _globals['_BOOKPAYLOAD']._serialized_start=161
  _globals['_BOOKPAYLOAD']._serialized_end=296
  _globals['_BOOKSERVICE']._serialized_start=299
  _globals['_BOOKSERVICE']._serialized_end=448
# @@protoc_insertion_point(module_scope)
