# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: follow.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'follow.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66ollow.proto\x12\x06\x66ollow\">\n\x12IsFollowingRequest\x12\x13\n\x0b\x66ollower_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x66ollowee_id\x18\x02 \x01(\x05\"(\n\x13IsFollowingResponse\x12\x11\n\tfollowing\x18\x01 \x01(\x08\"(\n\x15GetFollowStatsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"[\n\x16GetFollowStatsResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x17\n\x0f\x66ollowers_count\x18\x02 \x01(\x05\x12\x17\n\x0f\x66ollowing_count\x18\x03 \x01(\x05\"D\n\x14GetFollowListRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0c\n\x04skip\x18\x02 \x01(\x05\x12\r\n\x05limit\x18\x03 \x01(\x05\"8\n\x15GetFollowListResponse\x12\x10\n\x08user_ids\x18\x01 \x03(\x05\x12\r\n\x05total\x18\x02 \x01(\x05\x32\xc2\x02\n\rFollowService\x12\x46\n\x0bIsFollowing\x12\x1a.follow.IsFollowingRequest\x1a\x1b.follow.IsFollowingResponse\x12O\n\x0eGetFollowStats\x12\x1d.follow.GetFollowStatsRequest\x1a\x1e.follow.GetFollowStatsResponse\x12K\n\x0cGetFollowers\x12\x1c.follow.GetFollowListRequest\x1a\x1d.follow.GetFollowListResponse\x12K\n\x0cGetFollowing\x12\x1c.follow.GetFollowListRequest\x1a\x1d.follow.GetFollowListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'follow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ISFOLLOWINGREQUEST']._serialized_start=24
  _globals['_ISFOLLOWINGREQUEST']._serialized_end=86
  _globals['_ISFOLLOWINGRESPONSE']._serialized_start=88
  _globals['_ISFOLLOWINGRESPONSE']._serialized_end=128
  _globals['_GETFOLLOWSTATSREQUEST']._serialized_start=130
  _globals['_GETFOLLOWSTATSREQUEST']._serialized_end=170
  _globals['_GETFOLLOWSTATSRESPONSE']._serialized_start=172
  _globals['_GETFOLLOWSTATSRESPONSE']._serialized_end=263
  _globals['_GETFOLLOWLISTREQUEST']._serialized_start=265
  _globals['_GETFOLLOWLISTREQUEST']._serialized_end=333
  _globals['_GETFOLLOWLISTRESPONSE']._serialized_start=335
  _globals['_GETFOLLOWLISTRESPONSE']._serialized_end=391
  _globals['_FOLLOWSERVICE']._serialized_start=394
  _globals['_FOLLOWSERVICE']._serialized_end=716
# @@protoc_insertion_point(module_scope)
