# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    import follow_pb2 as follow__pb2
except ImportError:
    from proto import follow_pb2 as follow__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in follow_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FollowServiceStub(object):
    """──────────────────────────────────────────────────────────
    FollowService  –  exposed by the Follow service
    consumed by any downstream micro-service (e.g. User)
    ──────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IsFollowing = channel.unary_unary(
                '/follow.FollowService/IsFollowing',
                request_serializer=follow__pb2.IsFollowingRequest.SerializeToString,
                response_deserializer=follow__pb2.IsFollowingResponse.FromString,
                _registered_method=True)
        self.GetFollowStats = channel.unary_unary(
                '/follow.FollowService/GetFollowStats',
                request_serializer=follow__pb2.GetFollowStatsRequest.SerializeToString,
                response_deserializer=follow__pb2.GetFollowStatsResponse.FromString,
                _registered_method=True)
        self.GetFollowers = channel.unary_unary(
                '/follow.FollowService/GetFollowers',
                request_serializer=follow__pb2.GetFollowListRequest.SerializeToString,
                response_deserializer=follow__pb2.GetFollowListResponse.FromString,
                _registered_method=True)
        self.GetFollowing = channel.unary_unary(
                '/follow.FollowService/GetFollowing',
                request_serializer=follow__pb2.GetFollowListRequest.SerializeToString,
                response_deserializer=follow__pb2.GetFollowListResponse.FromString,
                _registered_method=True)


class FollowServiceServicer(object):
    """──────────────────────────────────────────────────────────
    FollowService  –  exposed by the Follow service
    consumed by any downstream micro-service (e.g. User)
    ──────────────────────────────────────────────────────────
    """

    def IsFollowing(self, request, context):
        """Check whether follower_id follows followee_id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFollowStats(self, request, context):
        """Get follower + following counts for a user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFollowers(self, request, context):
        """Get list of follower user_ids for a user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFollowing(self, request, context):
        """Get list of following user_ids for a user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FollowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IsFollowing': grpc.unary_unary_rpc_method_handler(
                    servicer.IsFollowing,
                    request_deserializer=follow__pb2.IsFollowingRequest.FromString,
                    response_serializer=follow__pb2.IsFollowingResponse.SerializeToString,
            ),
            'GetFollowStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFollowStats,
                    request_deserializer=follow__pb2.GetFollowStatsRequest.FromString,
                    response_serializer=follow__pb2.GetFollowStatsResponse.SerializeToString,
            ),
            'GetFollowers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFollowers,
                    request_deserializer=follow__pb2.GetFollowListRequest.FromString,
                    response_serializer=follow__pb2.GetFollowListResponse.SerializeToString,
            ),
            'GetFollowing': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFollowing,
                    request_deserializer=follow__pb2.GetFollowListRequest.FromString,
                    response_serializer=follow__pb2.GetFollowListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'follow.FollowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('follow.FollowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FollowService(object):
    """──────────────────────────────────────────────────────────
    FollowService  –  exposed by the Follow service
    consumed by any downstream micro-service (e.g. User)
    ──────────────────────────────────────────────────────────
    """

    @staticmethod
    def IsFollowing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/follow.FollowService/IsFollowing',
            follow__pb2.IsFollowingRequest.SerializeToString,
            follow__pb2.IsFollowingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFollowStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/follow.FollowService/GetFollowStats',
            follow__pb2.GetFollowStatsRequest.SerializeToString,
            follow__pb2.GetFollowStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFollowers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/follow.FollowService/GetFollowers',
            follow__pb2.GetFollowListRequest.SerializeToString,
            follow__pb2.GetFollowListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFollowing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/follow.FollowService/GetFollowing',
            follow__pb2.GetFollowListRequest.SerializeToString,
            follow__pb2.GetFollowListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
