# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/recommendation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/recommendation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/recommendation.proto\x12\x0erecommendation\"\x8c\x01\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x18\n\x10history_book_ids\x18\x02 \x03(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\x12\x11\n\tdiversify\x18\x04 \x01(\x08\x12\r\n\x05query\x18\x05 \x01(\t\x12\x17\n\x0f\x63urrent_book_id\x18\x06 \x01(\t\"d\n\x12\x42ookRecommendation\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x61uthors\x18\x03 \x03(\t\x12\r\n\x05score\x18\x04 \x01(\x02\x12\x0e\n\x06reason\x18\x05 \x01(\t\"U\n\x16RecommendationResponse\x12;\n\x0frecommendations\x18\x01 \x03(\x0b\x32\".recommendation.BookRecommendation\"]\n\x10InteractionEvent\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x62ook_id\x18\x02 \x01(\t\x12\x18\n\x10interaction_type\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x01\"K\n\x18UpdateUserProfileRequest\x12/\n\x05\x65vent\x18\x01 \x01(\x0b\x32 .recommendation.InteractionEvent\"=\n\x19UpdateUserProfileResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xe6\x01\n\x15RecommendationService\x12\x63\n\x12GetRecommendations\x12%.recommendation.RecommendationRequest\x1a&.recommendation.RecommendationResponse\x12h\n\x11UpdateUserProfile\x12(.recommendation.UpdateUserProfileRequest\x1a).recommendation.UpdateUserProfileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.recommendation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=47
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=187
  _globals['_BOOKRECOMMENDATION']._serialized_start=189
  _globals['_BOOKRECOMMENDATION']._serialized_end=289
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=291
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=376
  _globals['_INTERACTIONEVENT']._serialized_start=378
  _globals['_INTERACTIONEVENT']._serialized_end=471
  _globals['_UPDATEUSERPROFILEREQUEST']._serialized_start=473
  _globals['_UPDATEUSERPROFILEREQUEST']._serialized_end=548
  _globals['_UPDATEUSERPROFILERESPONSE']._serialized_start=550
  _globals['_UPDATEUSERPROFILERESPONSE']._serialized_end=611
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=614
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=844
# @@protoc_insertion_point(module_scope)
