# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommendation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'recommendation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14recommendation.proto\x12\x0erecommendation\"\xe7\x01\n\x0b\x42ookPayload\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x61uthors\x18\x03 \x03(\t\x12\x12\n\nauthor_ids\x18\x04 \x03(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x12\n\ncategories\x18\x06 \x03(\t\x12\x11\n\tthumbnail\x18\x07 \x01(\t\x12\x16\n\x0epublished_date\x18\x08 \x01(\t\x12\x10\n\x08language\x18\t \x01(\t\x12\x16\n\x0e\x61verage_rating\x18\n \x01(\x02\x12\x15\n\rratings_count\x18\x0b \x01(\x05\"?\n\x11IndexBooksRequest\x12*\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x1b.recommendation.BookPayload\"%\n\x12IndexBooksResponse\x12\x0f\n\x07indexed\x18\x01 \x01(\x05\"_\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\x17\n\x0f\x63urrent_book_id\x18\x03 \x01(\t\x12\r\n\x05limit\x18\x04 \x01(\x05\"d\n\x12\x42ookRecommendation\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x61uthors\x18\x03 \x03(\t\x12\r\n\x05score\x18\x04 \x01(\x02\x12\x0e\n\x06reason\x18\x05 \x01(\t\"U\n\x16RecommendationResponse\x12;\n\x0frecommendations\x18\x01 \x03(\x0b\x32\".recommendation.BookRecommendation2\xd1\x01\n\x15RecommendationService\x12S\n\nIndexBooks\x12!.recommendation.IndexBooksRequest\x1a\".recommendation.IndexBooksResponse\x12\x63\n\x12GetRecommendations\x12%.recommendation.RecommendationRequest\x1a&.recommendation.RecommendationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKPAYLOAD']._serialized_start=41
  _globals['_BOOKPAYLOAD']._serialized_end=272
  _globals['_INDEXBOOKSREQUEST']._serialized_start=274
  _globals['_INDEXBOOKSREQUEST']._serialized_end=337
  _globals['_INDEXBOOKSRESPONSE']._serialized_start=339
  _globals['_INDEXBOOKSRESPONSE']._serialized_end=376
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=378
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=473
  _globals['_BOOKRECOMMENDATION']._serialized_start=475
  _globals['_BOOKRECOMMENDATION']._serialized_end=575
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=577
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=662
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=665
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=874
# @@protoc_insertion_point(module_scope)
