# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/social.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/social.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/social.proto\x12\x06social\"#\n\x13GetBookStatsRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\t\"~\n\x16\x42ookSocialStatsPayload\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\x13\n\x0blikes_count\x18\x02 \x01(\x05\x12\x15\n\rratings_count\x18\x03 \x01(\x05\x12\x12\n\navg_rating\x18\x04 \x01(\x01\x12\x16\n\x0ehas_avg_rating\x18\x05 \x01(\x08\"\x0f\n\rHealthRequest\"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t2\x95\x01\n\rSocialService\x12K\n\x0cGetBookStats\x12\x1b.social.GetBookStatsRequest\x1a\x1e.social.BookSocialStatsPayload\x12\x37\n\x06Health\x12\x15.social.HealthRequest\x1a\x16.social.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.social_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETBOOKSTATSREQUEST']._serialized_start=30
  _globals['_GETBOOKSTATSREQUEST']._serialized_end=65
  _globals['_BOOKSOCIALSTATSPAYLOAD']._serialized_start=67
  _globals['_BOOKSOCIALSTATSPAYLOAD']._serialized_end=193
  _globals['_HEALTHREQUEST']._serialized_start=195
  _globals['_HEALTHREQUEST']._serialized_end=210
  _globals['_HEALTHRESPONSE']._serialized_start=212
  _globals['_HEALTHRESPONSE']._serialized_end=261
  _globals['_SOCIALSERVICE']._serialized_start=264
  _globals['_SOCIALSERVICE']._serialized_end=413
# @@protoc_insertion_point(module_scope)
