# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/user.proto\x12\x04user\"$\n\x11GetProfileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"\x91\x01\n\x12UserProfilePayload\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0b\n\x03\x62io\x18\x02 \x01(\t\x12\x12\n\navatar_url\x18\x03 \x01(\t\x12\x10\n\x08location\x18\x04 \x01(\t\x12\x0f\n\x07website\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\t\x12\x12\n\nupdated_at\x18\x07 \x01(\t\"\x0f\n\rHealthRequest\"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t2\x83\x01\n\x0bUserService\x12?\n\nGetProfile\x12\x17.user.GetProfileRequest\x1a\x18.user.UserProfilePayload\x12\x33\n\x06Health\x12\x13.user.HealthRequest\x1a\x14.user.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPROFILEREQUEST']._serialized_start=26
  _globals['_GETPROFILEREQUEST']._serialized_end=62
  _globals['_USERPROFILEPAYLOAD']._serialized_start=65
  _globals['_USERPROFILEPAYLOAD']._serialized_end=210
  _globals['_HEALTHREQUEST']._serialized_start=212
  _globals['_HEALTHREQUEST']._serialized_end=227
  _globals['_HEALTHRESPONSE']._serialized_start=229
  _globals['_HEALTHRESPONSE']._serialized_end=278
  _globals['_USERSERVICE']._serialized_start=281
  _globals['_USERSERVICE']._serialized_end=412
# @@protoc_insertion_point(module_scope)
